# docs/_config.yml
title: "Análisis Numérico con Python"
author: "Marco Cañas"
logo: "../images/logo_analisis_numerico.png"

execute:
  execute_notebooks: auto  # Opciones: 'auto', 'force', 'cache', 'off'

# Opciones de visualización
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true